### ISSUE TITLE
Alternative text voor images 

### ISSUE THREAD

**Issue by halie404** [ambersr/the-client-website#16]
### Code/Design Review Prototype en HTML

Je website design is heel mooi! 

Zorg dat je images een alternative title hebben bij sommige heb je dat wel maar soms mist het! 

Verder zit je html er goed uit. 

https://github.com/ambersr/the-client-website/blob/da87e386405b1b5ea98d96c9866b6884720b1992/index.html#L20

**Comment by ambersr** [comment]
Feedback is verwerkt:

Ik heb alle afbeeldingen een 'alt' gegeven. Commit: da26b0565925821772311d289f3fadd40efe0693

**Comment by ambersr** [comment]
Feedback is verwerkt:

Ik heb alle afbeeldingen een 'alt' gegeven. Commit: da26b0565925821772311d289f3fadd40efe0693
