### ISSUE TITLE
layout in css - Marcin en Jules

### ISSUE THREAD

**Issue by julesbruins** [ambersr/the-client-website#17]
- Waarom geef je content aan in [deze line](https://github.com/ambersr/the-client-website/blob/da87e386405b1b5ea98d96c9866b6884720b1992/styles/styles.css#L351-L353)? 
- Geef de buttons een align-items: center;.
- Waarom zijn er zoveel dubbele breakpoints, is dit nodig? (1200px) 
  - [https://github.com/ambersr/the-client-website/blob/da87e386405b1b5ea98d96c9866b6884720b1992/styles/styles.css#L521-L525](url) 
   - [https://github.com/ambersr/the-client-website/blob/da87e386405b1b5ea98d96c9866b6884720b1992/styles/styles.css#L587-L597](url) + nog meer...
- Gebruik ipv value, placeholders op inputs.

**Comment by ambersr** [comment]
Ik heb de feedback verwerkt:

- De cijfer code in [deze lijn](https://github.com/ambersr/the-client-website/blob/da87e386405b1b5ea98d96c9866b6884720b1992/styles/styles.css#L351-L353) is een icon. Ik heb er nu een comment bijgeschreven! Commit: https://github.com/ambersr/the-client-website/commit/2fd87395f36e459b6c52c447cb147a7b0b0ef6c3
- De buttons heb ik een align-items: center; gegeven. Commit: 
- Ik heb mobile first gewerkt. Ik heb daarom 3 breakpoints toegevoegd: 740px, 1000px, 1200px. De breakpoint 1200px heb ik toegevoegd omdat anders de content van de pagina op schermen vanaf 1200px te dicht op rand zitten.
- De 'value' heb ik vervangen voor 'placeholder' in de form. Commit: https://github.com/ambersr/the-client-website/commit/2fd87395f36e459b6c52c447cb147a7b0b0ef6c3

**Comment by ambersr** [comment]
Ik heb de feedback verwerkt:

- De cijfer code in [deze lijn](https://github.com/ambersr/the-client-website/blob/da87e386405b1b5ea98d96c9866b6884720b1992/styles/styles.css#L351-L353) is een icon. Ik heb er nu een comment bijgeschreven! Commit: eebf7a97fe452cafc861f53d74d0c4655d03d230
- De buttons heb ik een align-items: center; gegeven. Commit: e5682758390b417b70e3d4b4319af0dc71959a4f
- Ik heb mobile first gewerkt. Ik heb daarom 3 breakpoints toegevoegd: 740px, 1000px, 1200px. De breakpoint 1200px heb ik toegevoegd omdat anders de content van de pagina op schermen vanaf 1200px te dicht op rand zitten.
- De 'value' heb ik vervangen voor 'placeholder' in de form. Commit: https://github.com/ambersr/the-client-website/commit/2fd87395f36e459b6c52c447cb147a7b0b0ef6c3
