### ISSUE TITLE
Style property in HTML

### ISSUE THREAD

**Issue by Robin1224** [ambersr/the-client-website#2]
Op een aantal van de foto's heb je een `style` attribuut staan waarmee je de hoogte van de foto aangeeft. 

https://github.com/ambersr/the-client-website/blob/efee0280ccf8f89297a63261b28b546149463b75/index.html#L16

In principe wil je zo weinig mogelijk `style` attributen gebruiken binnen je HTML. Het helpt namelijk om overzicht te bewaren als je HTML, CSS en Javascript allemaal zijn eigen taak hebben; HTML voor structuur, CSS voor styling en Javascript voor interactiviteit. Wanneer je `style` attributen gebruikt in je HTML zet je eigenlijk styling binnen je HTML, terwijl dit een taak is voor jouw CSS.

Dit concept heet "Separation of concerns", en is een code conventie dat veel aangehouden wordt. [Meer info](https://medium.com/@dennis.pintilie.alexandru/separation-of-concerns-soc-fd72b0191b1f)

**Suggestie:** Je kunt de style tag gewoon helemaal weglaten. Je pagina hoeft er zonder CSS niet goed uit te zien, als de structuur maar goed is. Een foto die zonder CSS te groot is is daarom geen probleem.

**Comment by ambersr** [comment]
Ik heb de CSS uit de HTML gehaald, zie commit:

dd4a55d71675aed47c03ef98dd8c5ed6e52de026
