### ISSUE TITLE
Feedback readMe

### ISSUE THREAD

**Issue by wingsvn** [ambersr/the-client-website#22]
Je zou misschien nog wat meer kunnen vertellen over bieb in bloei zelf. 
In je readMe staat verder duidelijk beschreven hoe je website werkt en waar de website uit bestaat en welke technieken je hebt gebruikt. Je laat dit ook goed zien aan de hand van foto's, wellicht misschien iets te veel, haha. Kijk nog even goed welke aspecten op de pagina je echt wil uitlichten. De lezer kan namelijk de rest van de website bezoeken via de live link :)

Verder is het heel professioneel en duidelijk!

**Comment by ambersr** [comment]
Top dankjewel! Ik heb het gelijk aangepast. Commit: https://github.com/ambersr/the-client-website/commit/ab845de6b49fc67b02db661359f6e2cbf5f975c2
