### ISSUE TITLE
Onjuist gebruik van <sup> element

### ISSUE THREAD

**Issue by Robin1224** [ambersr/the-client-website#3]
In jouw HTML code gebruik je voor tekst bij foto's het `<sup>` element.

https://github.com/ambersr/the-client-website/blob/efee0280ccf8f89297a63261b28b546149463b75/index.html#L26-L29

Ik neem aan dat je dit element gekozen hebt omdat het kleiner is, maar dit is eigenlijk niet waar het voor bedoeld is. Het `<sup>` element is bedoeld voor wanneer je tekst binnen een zin hoger wil hebben staan dan de rest van de zin, voor bijvoorbeeld kwadraten of citaten. [Meer info](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sup)

**Suggestie:** Je kunt de `<sup>` elementen in jouw HTML beter vervangen met een `<p>` element, en deze via CSS straks kleiner maken. Dit behoudt ook de Separation of Concerns ([Meer info](https://medium.com/@dennis.pintilie.alexandru/separation-of-concerns-soc-fd72b0191b1f)), een code conventie die ernaar streeft om structuur (HTML) en styling (CSS) compleet apart te houden zodat je meer overzicht kan behouden. Een tekst kleiner maken is in dit geval dus een taak voor CSS, niet voor HTML.

**Comment by ambersr** [comment]
Ik heb de sup element vervangen voor p element, zie commit:

f34cdc0208d92c7c9e394d3f1bd333ca503408c0

**Comment by ambersr** [comment]
Ik heb de sup element vervangen voor p element, zie commit:

f34cdc0208d92c7c9e394d3f1bd333ca503408c0
