### ISSUE TITLE
Figcaptions & lists

### ISSUE THREAD

**Issue by Saif8599** [ambersr/the-client-website#4]
Je kan in je figure beter gebruik maken van figcaptions ipv van een p element. 
https://github.com/ambersr/the-client-website/blob/main/index.html#L142-L147

Verder kan je de navigatie items beter in een list zetten net als in de footer (styling en overzicht).
https://github.com/ambersr/the-client-website/blob/main/index.html#L15-L25

Om een semantische structuur te creëren kan je het beste de navigatie binnen de header plaatsen en de kerninhoud in de main. Dit zorgt voor een duidelijke structuur en leesbare code.

-Saif en Colin

**Comment by ambersr** [comment]
Ik heb de img uit de figure gehaald en de navigatie items in een list geplaatst, zie commit:

Commit voor de afbeelding:
ffb47a2c8798edb6b33faf680e0713ef843369ac
Commit voor de navigatie items uit de list gehaald:
25f419f51dbff1113eb330a27b25b0ccb1fb375b

**Comment by ambersr** [comment]
Ik heb de img uit de figure gehaald en de navigatie items in een list geplaatst, zie commits:

Commit voor de afbeelding:
ffb47a2c8798edb6b33faf680e0713ef843369ac
Commit voor de navigatie items uit de list gehaald:
25f419f51dbff1113eb330a27b25b0ccb1fb375b
