### ISSUE TITLE
Gebruik geen CSS in de html

### ISSUE THREAD

**Issue by KoopReynders** [ambersr/the-client-website#5]
https://github.com/ambersr/the-client-website/blob/efee0280ccf8f89297a63261b28b546149463b75/index.html#L16

Probeer de CSS en HTML te scheiden. Schrijf alle CSS in je style file. 
In HTML kun je een image ook een hoogte en breedte meegeven.

**Comment by ambersr** [comment]
Ik heb de CSS uit de HTML gehaald, zie commit:

dd4a55d71675aed47c03ef98dd8c5ed6e52de026

**Comment by ambersr** [comment]
Ik heb de CSS uit de HTML gehaald, zie commit:

dd4a55d71675aed47c03ef98dd8c5ed6e52de026
