### ISSUE TITLE
Klopt <sup>: The Superscript element ?

### ISSUE THREAD

**Issue by KoopReynders** [ambersr/the-client-website#6]
https://github.com/ambersr/the-client-website/blob/efee0280ccf8f89297a63261b28b546149463b75/index.html#L28

Je gebruikt op verschillende plekken het `<sup>` element. Ik weet niet of dit klopt. 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sup

**Comment by ambersr** [comment]
Ik heb dit nagezocht. De sup element is inderdaad niet op de juiste manier gebruikt. Het sup element heb ik nu vervangen voor een p element. (zie commit)

f34cdc0208d92c7c9e394d3f1bd333ca503408c0

**Comment by ambersr** [comment]
Ik heb dit nagezocht. De sup element is inderdaad niet op de juiste manier gebruikt. Het sup element heb ik nu vervangen voor een p element. (zie commit)

f34cdc0208d92c7c9e394d3f1bd333ca503408c0
