### ISSUE TITLE
Gebruik van Figure

### ISSUE THREAD

**Issue by KoopReynders** [ambersr/the-client-website#7]
https://github.com/ambersr/the-client-website/blob/efee0280ccf8f89297a63261b28b546149463b75/index.html#L35-L37

Een `<figure>` wordt over het algemeen gebruikt als een image een caption heeft en/of als je naar een figure wil verwijzen. Omdat je dat hier niet doet, kan dan de `<figure>` weg? 

Moet de image in de <`section>`? Zo heb je dat wel bij onderstaande sections.

**Comment by ambersr** [comment]
Ik heb figure eruit gehaald, want de img staat inderdaad al in een section. (zie commit)

ffb47a2c8798edb6b33faf680e0713ef843369ac
